markdown: kramdown
highlighter: rouge
destination: _httpdocs
url: tmpworldwide.dev
repo: https://github.com/tmpworldwide/tmpworldwide.github.io/
ghpage: https://tmpworldwide.dev/
sass:
    style: :compressed
exclude: [
  README.md
]
